Pull request for issue #55
tox-dev/sphinx-argparse-cli pull request #56
Opened 2022-08-08 17:07 UTC by berhoel

I added option `no_default_values` with test.

2022-08-08 17:50 UTC, gaborbernat commented
Please never put an issue number into the description of a PR. Just put the change description the PR introduces.

2022-08-08 17:52 UTC, gaborbernat requested changes

2022-08-08 17:52 UTC, gaborbernat commented on roots/test-default-handling/index.rst
> +  :no_default_values: false
What's with the double negative here? Either make this not take an argument or drop the no prefix.

2022-08-08 17:53 UTC, gaborbernat commented on roots/test-default-handling/index.rst
> +  :no_default_values: false
Also, add a changelog entry.

2022-08-08 19:03 UTC, berhoel commented
I made the changes as requested in the above comment.

I hope it is OK to introduce a new version number in the change log.

Sorry for the error in the test input file.

2022-08-09 06:57 UTC, gaborbernat requested changes

2022-08-09 06:57 UTC, gaborbernat commented on CHANGELOG.md
> +## 1.9.1
This is a feature so should be `1.10.0` per semver rules.

2022-08-09 10:46 UTC, berhoel commented
Thank you for your review.

I changed the version number in CHANGELOG.md.

2022-08-09 16:11 UTC, gaborbernat approved these changes

2022-08-09 16:13 UTC, merged